### PR TITLE
Added widget to customer frontend

### PR DESCRIPTION
**Pull request by edicarloslds**
Added widget to show the quota available in the customer interface.

### CODE REVIEW

**Comment by denydias** [comment]
Dear @edicarloslds, that's indeed a fantastic PR! :clap:

I'm going to review your PR in the days to come and hopefully merge it to master by the end of this week. A new release is going to be available shortly after that.

Thank you very much for this enhancement and for pushing it.

**Comment by edicarloslds** [comment]
@denydias  Great!!  
thanks.

**Comment by denydias** [comment]
@edicarloslds, sorry for the delay.

I just reviewed your contribution. Apart for some minor tidy and licensing sutff, it looks good to go. The way you've found to display available quota across the whole Customer interface is quite elegant.

Thank you for your PR. I'll release it in no time.

**Comment by edicarloslds** [comment]
@denydias Great! 
I'm just happy to contribute.

**Pull request merged**
